In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls

 Baseline.pdf
'BERT has a mouth, so it must speak.pdf'
'Cover Letter.txt'
'Data Analysis.ipynb'
'Extracting training data from large language models.pdf'
 gre_math_review.pdf
'List of doubts.txt'
'Minor Project'
 MLM_Project
'Monte Carlo Sampling Algos.pdf'
'Multi Hop QnA.pdf'
'Shuffle Model.pdf'


In [3]:
data = pd.read_csv('/home/archit/Documents/Minor Project/Dataset.csv')

In [4]:
data.head()

Unnamed: 0                                        description  \
0           0   A 23-year-old white female presents with comp...   
1           1           Consult for laparoscopic gastric bypass.   
2           2           Consult for laparoscopic gastric bypass.   
3           3                             2-D M-Mode. Doppler.     
4           4                                 2-D Echocardiogram   

             medical_specialty                                sample_name  \
0         Allergy / Immunology                         Allergic Rhinitis    
1                   Bariatrics   Laparoscopic Gastric Bypass Consult - 2    
2                   Bariatrics   Laparoscopic Gastric Bypass Consult - 1    
3   Cardiovascular / Pulmonary                    2-D Echocardiogram - 1    
4   Cardiovascular / Pulmonary                    2-D Echocardiogram - 2    

                                       transcription  \
0  SUBJECTIVE:,  This 23-year-old white female pr...   
1  PAST MEDICAL HISTORY:, He has difficulty climb...   
2  HISTORY OF PRESENT ILLNESS: , I have seen ABC ...   
3  2-D M-MODE: , ,1.  Left atrial enlargement wit...   
4  1.  The left ventricular cavity size and wall ...   

                                            keywords  
0  allergy / immunology, allergic rhinitis, aller...  
1  bariatrics, laparoscopic gastric bypass, weigh...  
2  bariatrics, laparoscopic gastric bypass, heart...  
3  cardiovascular / pulmonary, 2-d m-mode, dopple...  
4  cardiovascular / pulmonary, 2-d, doppler, echo...

In [5]:
len(data)

4999

In [6]:
data.iloc[0, 4]

'SUBJECTIVE:,  This 23-year-old white female presents with complaint of allergies.  She used to have allergies when she lived in Seattle but she thinks they are worse here.  In the past, she has tried Claritin, and Zyrtec.  Both worked for short time but then seemed to lose effectiveness.  She has used Allegra also.  She used that last summer and she began using it again two weeks ago.  It does not appear to be working very well.  She has used over-the-counter sprays but no prescription nasal sprays.  She does have asthma but doest not require daily medication for this and does not think it is flaring up.,MEDICATIONS: , Her only medication currently is Ortho Tri-Cyclen and the Allegra.,ALLERGIES: , She has no known medicine allergies.,OBJECTIVE:,Vitals:  Weight was 130 pounds and blood pressure 124/78.,HEENT:  Her throat was mildly erythematous without exudate.  Nasal mucosa was erythematous and swollen.  Only clear drainage was seen.  TMs were clear.,Neck:  Supple without adenopathy.,

In [7]:
unique_desc = np.unique(data.iloc[:, 1])
print(unique_desc)

[' '
 '  Antibiotic management for a right foot ulcer and possible osteomyelitis.'
 '  CT abdomen without contrast and pelvis without contrast, reconstruction.'
 ...
 ' Wrist de Quervain stenosing tenosynovitis.  de Quervain release.  Fascial lengthening flap of the 1st dorsal compartment.'
 ' X-RAY of the soft tissues of the neck.'
 ' Youngswick osteotomy with internal screw fixation of the first right metatarsophalangeal joint of the right foot.']


In [8]:
unique_med_sp = np.unique(data.iloc[:, 2])
print(unique_med_sp)

[' Allergy / Immunology' ' Autopsy' ' Bariatrics'
 ' Cardiovascular / Pulmonary' ' Chiropractic'
 ' Consult - History and Phy.' ' Cosmetic / Plastic Surgery' ' Dentistry'
 ' Dermatology' ' Diets and Nutritions' ' Discharge Summary'
 ' ENT - Otolaryngology' ' Emergency Room Reports' ' Endocrinology'
 ' Gastroenterology' ' General Medicine' ' Hematology - Oncology'
 ' Hospice - Palliative Care' ' IME-QME-Work Comp etc.'
 ' Lab Medicine - Pathology' ' Letters' ' Nephrology' ' Neurology'
 ' Neurosurgery' ' Obstetrics / Gynecology' ' Office Notes'
 ' Ophthalmology' ' Orthopedic' ' Pain Management'
 ' Pediatrics - Neonatal' ' Physical Medicine - Rehab' ' Podiatry'
 ' Psychiatry / Psychology' ' Radiology' ' Rheumatology'
 ' SOAP / Chart / Progress Notes' ' Sleep Medicine' ' Speech - Language'
 ' Surgery' ' Urology']


In [9]:
unique_name = np.unique(data.iloc[:, 3])
print(unique_name)

[' 1-year-old Exam - H&P ' ' 2-D Doppler ' ' 2-D Echocardiogram - 1 ' ...
 ' Youngswick Osteotomy ' ' de Quervain Release - Carpal '
 ' de Quervain Release - Wrist ']


In [10]:
unique_trans = np.unique(data.iloc[:, 4].astype(str))
print(len(unique_trans))

2358


In [24]:
unique_keys = np.unique(data.iloc[:, 5].astype(str))
print(len(unique_keys))

3850


In [14]:
for i in range(len(unique_desc)):
    print(np.where(data.description == unique_desc[i]))

(array([ 766, 1292, 2807, 3679, 4261, 4565]),)
(array([3448, 4575]),)
(array([1707, 3038, 3604]),)
(array([1687, 2268, 2923]),)
(array([ 450, 2404]),)
(array([1441, 4894]),)
(array([ 884, 4826]),)
(array([ 849, 4813]),)
(array([1298, 3112]),)
(array([ 661, 2188]),)
(array([1243, 2340, 2731]),)
(array([ 478, 4717]),)
(array([703]),)
(array([ 349, 4670]),)
(array([ 660, 2693]),)
(array([ 663, 2191]),)
(array([1129, 4938]),)
(array([ 578, 2569]),)
(array([1075, 2283]),)
(array([ 561, 1835, 2157]),)
(array([ 256, 2026]),)
(array([1210, 2325]),)
(array([ 317, 2532]),)
(array([  14, 1155]),)
(array([3222, 3899]),)
(array([3325, 4366]),)
(array([1913, 3906]),)
(array([1898, 4133]),)
(array([ 268, 3703]),)
(array([ 627, 2591]),)
(array([ 36, 240]),)
(array([2911, 3948]),)
(array([1946, 4021]),)
(array([1877, 4087]),)
(array([1882, 4086]),)
(array([3369, 4401]),)
(array([3366, 4397]),)
(array([1933, 3762, 4441]),)
(array([   4,    7, 1753, 1755]),)
(array([   3, 1758]),)
(array([3865, 4954]),)


(array([3976, 4852]),)
(array([ 508, 2117]),)
(array([1460, 3212]),)
(array([ 195, 2665, 2760]),)
(array([ 158, 1028]),)
(array([ 162, 1034]),)
(array([ 160, 1040]),)
(array([ 161, 1033]),)
(array([ 168, 1031]),)
(array([ 152, 1030, 1934]),)
(array([ 153, 1038, 1940]),)
(array([1022, 2428]),)
(array([1027, 3774]),)
(array([3047, 4522]),)
(array([2869, 4336]),)
(array([ 421, 2066]),)
(array([ 596, 2173]),)
(array([ 558, 4043]),)
(array([1014, 2265]),)
(array([1012, 2272]),)
(array([ 169, 1169]),)
(array([ 312, 3469]),)
(array([1019]),)
(array([389]),)
(array([1997]),)
(array([1286, 3970]),)
(array([ 466, 4706]),)
(array([1017, 3771]),)
(array([1009, 3653]),)
(array([ 996, 3634]),)
(array([ 998, 3642]),)
(array([ 994, 3636]),)
(array([1015, 3658]),)
(array([1006, 3648]),)
(array([ 990, 3635]),)
(array([ 997, 3639]),)
(array([ 991, 3640]),)
(array([ 981, 3623]),)
(array([ 976, 3619]),)
(array([ 973, 3620]),)
(array([1008, 3644]),)
(array([ 988, 3628]),)
(array([1001, 3649]),)
(array([1010

(array([ 292, 2669, 2764]),)
(array([1945]),)
(array([1891, 4123]),)
(array([2937]),)
(array([1203, 2311]),)
(array([1183, 3675]),)
(array([ 741, 2212]),)
(array([2216, 3915]),)
(array([ 908, 2619]),)
(array([ 909, 2623]),)
(array([1249, 2347, 2738]),)
(array([1256, 2363, 2754]),)
(array([1984]),)
(array([  26, 3881]),)
(array([3329, 4355]),)
(array([3205, 4102]),)
(array([2359, 4579]),)
(array([3474, 4127]),)
(array([ 279, 2035]),)
(array([3287, 4343]),)
(array([1650, 1880, 2901]),)
(array([1003, 3650]),)
(array([1358, 2177]),)
(array([148, 946]),)
(array([4769]),)
(array([4765]),)
(array([4768]),)
(array([4766]),)
(array([3109]),)
(array([3108]),)
(array([3103]),)
(array([1369, 3279]),)
(array([1365, 3282]),)
(array([1629, 3157]),)
(array([3412, 3960]),)
(array([4075, 4556]),)
(array([109, 717]),)
(array([111, 722]),)
(array([112, 725]),)
(array([3276, 3920]),)
(array([ 715, 2596]),)
(array([2637, 3975]),)
(array([ 477, 4721]),)
(array([ 475, 4714]),)
(array([1165, 4946]),)
(array([1

(array([1306, 2771]),)
(array([1498, 2515]),)
(array([1350, 1466, 3230]),)
(array([1463, 4145, 4689]),)
(array([ 960, 2716, 2941]),)
(array([3093, 3095, 3100, 4203, 4206, 4212]),)
(array([3096, 4207]),)
(array([1870, 3897]),)
(array([1367, 3294]),)
(array([2429, 4463]),)
(array([1828]),)
(array([1824]),)
(array([ 323, 3470]),)
(array([1043, 3669]),)
(array([ 491, 4033]),)
(array([ 57, 404]),)
(array([ 488, 2098]),)
(array([2114, 3894]),)
(array([ 482, 2096]),)
(array([ 486, 2100, 4034]),)
(array([ 480, 2103]),)
(array([ 490, 2107]),)
(array([ 492, 2104]),)
(array([ 495, 2111]),)
(array([ 484, 2099]),)
(array([ 497, 2108]),)
(array([ 340, 3719]),)
(array([ 487, 2101]),)
(array([ 498, 2109]),)
(array([ 532, 3740]),)
(array([ 463, 2072]),)
(array([ 351, 3717]),)
(array([1342, 1344, 2411, 2422]),)
(array([ 79, 494]),)
(array([2794, 4205]),)
(array([1343, 2085]),)
(array([1112, 4922]),)
(array([ 481, 2086]),)
(array([1976]),)
(array([1334, 1866]),)
(array([  73, 1337]),)
(array([ 435, 4710]

(array([ 364, 2382]),)
(array([ 353, 2377]),)
(array([ 361, 2380]),)
(array([1005, 3641]),)
(array([ 676, 2420]),)
(array([3265, 3486, 3904, 4728]),)
(array([1262, 4968]),)
(array([ 354, 4675]),)
(array([ 970, 4848]),)
(array([ 746, 4780]),)
(array([ 967, 4853]),)
(array([1624, 2871]),)
(array([566]),)
(array([1387, 3320]),)
(array([3421, 4481]),)
(array([3125, 3210, 4128]),)
(array([1346, 2998]),)
(array([ 357, 3714]),)
(array([2769, 3209, 4130]),)
(array([3755, 4428]),)
(array([1980]),)
(array([3259, 3821]),)
(array([1304, 3471]),)
(array([2434, 4513]),)
(array([ 918, 2625]),)
(array([ 900, 2618]),)
(array([1765, 4152]),)
(array([ 249, 2378]),)
(array([1375, 3304]),)
(array([3367, 4404]),)
(array([1708, 4843]),)
(array([2059, 4138]),)
(array([4129, 4665]),)
(array([ 348, 3476]),)
(array([3857, 4047]),)
(array([ 476, 4719]),)
(array([1531, 1892]),)
(array([ 465, 4712]),)
(array([1335, 4707]),)
(array([ 360, 3998]),)
(array([1552, 1915]),)
(array([1465, 2772]),)
(array([ 979, 3625]),)


In [20]:
fields = []
for col in data.columns:
    fields.append(col)
fields = fields[1:]
print(fields)

['description', 'medical_specialty', 'sample_name', 'transcription', 'keywords']


In [21]:
for i in range(len(unique_med_sp)):
    print(np.where(data[fields[1]] == unique_med_sp[i]))

(array([   0, 4993, 4994, 4995, 4996, 4997, 4998]),)
(array([4981, 4983, 4986, 4987, 4988, 4990, 4991, 4992]),)
(array([   1,    2,    5,    6,    8,   10,   13,   15,   17,   21, 4977,
       4978, 4979, 4980, 4982, 4984, 4985, 4989]),)
(array([   3,    4,    7,    9,   11,   16, 4609, 4611, 4612, 4613, 4614,
       4616, 4617, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4625, 4626,
       4627, 4628, 4629, 4630, 4631, 4632, 4633, 4634, 4635, 4636, 4637,
       4638, 4639, 4640, 4641, 4642, 4643, 4644, 4645, 4646, 4647, 4648,
       4649, 4650, 4651, 4652, 4653, 4654, 4655, 4656, 4657, 4658, 4659,
       4660, 4661, 4662, 4663, 4664, 4665, 4666, 4667, 4668, 4669, 4670,
       4671, 4672, 4673, 4674, 4675, 4676, 4677, 4678, 4679, 4680, 4681,
       4682, 4683, 4684, 4685, 4686, 4687, 4688, 4689, 4690, 4691, 4692,
       4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703,
       4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4714,
       4715, 4716, 4717, 4718, 

In [22]:
for i in range(len(unique_name)):
    print(np.where(data[fields[2]] == unique_name[i]))

(array([1945]),)
(array([  11, 1764]),)
(array([   3, 1758]),)
(array([   4, 1753]),)
(array([   7, 1755]),)
(array([   9, 1756]),)
(array([1754, 3204]),)
(array([1948, 4595]),)
(array([1276, 2364]),)
(array([1196, 3056]),)
(array([1194, 3063]),)
(array([1193, 3055]),)
(array([1190, 3051]),)
(array([1192, 3050]),)
(array([1751, 2967]),)
(array([1279, 3688]),)
(array([1278, 3689]),)
(array([3461, 3683, 3883, 4602]),)
(array([1284, 2660]),)
(array([3080]),)
(array([4592, 4976]),)
(array([2499, 4588, 4975]),)
(array([3879, 4587]),)
(array([1277, 3684]),)
(array([1857, 3994]),)
(array([3460, 3878]),)
(array([1273, 2367]),)
(array([2365]),)
(array([1275, 2360]),)
(array([1453, 4027]),)
(array([4031]),)
(array([4032, 4589]),)
(array([1452, 3811]),)
(array([2007]),)
(array([3459, 3808, 4591]),)
(array([3882, 4594, 4973]),)
(array([1750, 2976]),)
(array([3054]),)
(array([1269]),)
(array([1270, 3784]),)
(array([1274, 3787]),)
(array([1264, 3781]),)
(array([1749, 4972]),)
(array([1263, 3783]),)


(array([3048]),)
(array([1429, 3045]),)
(array([1432, 3043]),)
(array([1431, 3431]),)
(array([1942, 3767, 4523]),)
(array([4529, 4994]),)
(array([1037, 4865]),)
(array([1036, 4862]),)
(array([ 164, 1041]),)
(array([ 158, 1028]),)
(array([ 162, 1034]),)
(array([ 160, 1040]),)
(array([ 161, 1033]),)
(array([ 166, 1035]),)
(array([ 167, 1032]),)
(array([ 168, 1031]),)
(array([ 159, 1029]),)
(array([ 153, 1038, 1940]),)
(array([ 152, 1030, 1934]),)
(array([ 151, 1026, 1939]),)
(array([ 156, 1428]),)
(array([1022, 2428]),)
(array([1020, 3772]),)
(array([1027, 3774]),)
(array([3047, 4522]),)
(array([3864]),)
(array([1021, 2269]),)
(array([1023, 2270]),)
(array([1024, 2275]),)
(array([1025, 4054]),)
(array([1014, 2265]),)
(array([1012, 2272]),)
(array([1426, 3657]),)
(array([1016, 4079]),)
(array([1019]),)
(array([1013, 4863]),)
(array([1997]),)
(array([1286, 3970]),)
(array([1017, 3771]),)
(array([3182, 3656, 4518]),)
(array([3176, 3652, 4516]),)
(array([3175, 3659, 4520]),)
(array([1018, 36

(array([1398, 3386]),)
(array([2233]),)
(array([2707, 2884, 4424]),)
(array([2605, 4425]),)
(array([ 795, 3011, 4799]),)
(array([1630, 2229]),)
(array([ 128, 3378, 4429]),)
(array([ 131, 3377, 4423]),)
(array([ 790, 4063]),)
(array([ 798, 3544]),)
(array([ 793, 3537]),)
(array([ 791, 3538]),)
(array([ 797, 3542]),)
(array([ 792, 4794]),)
(array([124, 789]),)
(array([125, 781]),)
(array([ 782, 4795]),)
(array([ 788, 4798]),)
(array([ 785, 3746]),)
(array([ 784, 2227]),)
(array([ 787, 3010, 4791]),)
(array([1402, 2235]),)
(array([3376, 4789, 4996]),)
(array([1841, 4418]),)
(array([ 778, 1400, 1840]),)
(array([1844, 3840]),)
(array([1392]),)
(array([2224, 4420, 4600]),)
(array([3373, 4416]),)
(array([1930, 3374, 3848, 4422]),)
(array([ 779, 1842, 2222]),)
(array([ 780, 1839, 2226]),)
(array([783]),)
(array([123, 776]),)
(array([ 121, 1395]),)
(array([ 122, 3536, 4419]),)
(array([ 786, 2708, 2876]),)
(array([ 777, 2703]),)
(array([ 773, 4044]),)
(array([ 771, 4041]),)
(array([1628, 2608]),

(array([ 581, 2573]),)
(array([ 580, 2568]),)
(array([ 578, 2569]),)
(array([ 585, 2570]),)
(array([ 583, 2565]),)
(array([ 579, 2566]),)
(array([ 584, 2564]),)
(array([1619, 4751]),)
(array([1979, 2171]),)
(array([1613, 4750]),)
(array([3488, 4288]),)
(array([2167, 4294]),)
(array([ 576, 2168]),)
(array([ 568, 1617, 1973, 2166, 2855]),)
(array([1974]),)
(array([1978]),)
(array([1970]),)
(array([1971]),)
(array([1977]),)
(array([ 575, 2164, 2696]),)
(array([ 573, 2162, 2697]),)
(array([ 569, 2170, 2692]),)
(array([ 570, 2690, 2856]),)
(array([ 574, 2695, 2853]),)
(array([ 572, 2165, 2694]),)
(array([2159, 4289]),)
(array([ 571, 2160, 2687]),)
(array([2163, 4292]),)
(array([1975]),)
(array([2850, 4295]),)
(array([566]),)
(array([1356, 4753]),)
(array([3089, 4743]),)
(array([3086, 4745]),)
(array([3102, 3146, 4293, 4739]),)
(array([1355, 3148]),)
(array([3084, 4748]),)
(array([ 567, 3150]),)
(array([3145, 3275, 4291, 4744]),)
(array([3151, 4290]),)
(array([ 565, 2563]),)
(array([2849, 42

(array([1785, 4166]),)
(array([1783, 4159]),)
(array([1777, 4160]),)
(array([1781, 4162]),)
(array([1782, 4163]),)
(array([1780, 4164]),)
(array([1775, 4161]),)
(array([1779, 4156]),)
(array([1778, 4155]),)
(array([1774]),)
(array([1776, 4158]),)
(array([1773, 4157]),)
(array([1765, 4152]),)
(array([1770, 3886]),)
(array([1772, 3890]),)
(array([1766, 3887]),)
(array([1769]),)
(array([1767]),)
(array([1771]),)
(array([1768]),)
(array([1759]),)
(array([1761]),)
(array([1763, 2989]),)
(array([1762, 2992]),)
(array([1760, 2986]),)
(array([ 409, 2675]),)
(array([  49, 4146]),)
(array([1317, 4694]),)
(array([ 407, 4692]),)
(array([1463, 4145, 4689]),)
(array([4147, 4690]),)
(array([4149, 4684]),)
(array([4154, 4685]),)
(array([4688]),)
(array([4686]),)
(array([4691]),)
(array([4687]),)
(array([4683]),)
(array([4678]),)
(array([1907, 4151, 4681]),)
(array([1314, 4682]),)
(array([ 398, 4680]),)
(array([ 401, 3999]),)
(array([ 397, 4006]),)
(array([2985, 3228, 3889]),)
(array([  55,  400, 2981]

In [23]:
for i in range(len(unique_trans)):
    print(np.where(data[fields[3]] == unique_trans[i]))

(array([ 874, 3577]),)
(array([ 110,  719, 2598]),)
(array([   4, 1753]),)
(array([   7, 1755]),)
(array([   3, 1758]),)
(array([  11, 1764]),)
(array([1754, 3204]),)
(array([ 230, 2522]),)
(array([ 986, 3624]),)
(array([1342, 2411]),)
(array([3080]),)
(array([4031]),)
(array([2007]),)
(array([1270, 3784]),)
(array([2118, 3907]),)
(array([2216, 3915]),)
(array([3412, 3960]),)
(array([3407, 3951]),)
(array([2606, 3914]),)
(array([2604, 3919]),)
(array([3227, 3898, 4699]),)
(array([3895, 4695]),)
(array([2985, 3228, 3889]),)
(array([3265, 3486, 3904, 4728]),)
(array([2637, 3975]),)
(array([2536, 3880]),)
(array([3884]),)
(array([3401, 3953]),)
(array([  64, 4177]),)
(array([2306, 3981]),)
(array([1867, 2211, 4325]),)
(array([2600, 3910]),)
(array([2114, 3894]),)
(array([3594, 3946]),)
(array([3222, 3899]),)
(array([3410, 3965]),)
(array([3013, 3930]),)
(array([3942, 4984]),)
(array([2193, 3912]),)
(array([3979, 4899]),)
(array([1768]),)
(array([3534, 3922]),)
(array([1932, 3923]),)
(arra

(array([1575, 2821]),)
(array([1578, 2822]),)
(array([1616]),)
(array([1738, 2655]),)
(array([1682, 2254, 2917]),)
(array([1542, 3128]),)
(array([1545]),)
(array([1533, 2978]),)
(array([1531, 1892]),)
(array([1552, 1915]),)
(array([ 470, 1541, 3477]),)
(array([1659, 2904]),)
(array([1587, 2151, 2830]),)
(array([1576, 1825, 2143]),)
(array([1579, 2139]),)
(array([1577, 2140]),)
(array([1572, 2134]),)
(array([1561, 2127]),)
(array([1557, 2136]),)
(array([1560, 2129]),)
(array([1571, 2142]),)
(array([1608, 1834, 2152]),)
(array([1611, 1827, 2155]),)
(array([1580, 1826, 2141]),)
(array([1573, 2133]),)
(array([1562, 2135]),)
(array([1589, 2148, 2827]),)
(array([1568, 2138]),)
(array([1574, 1829, 2144]),)
(array([1103, 4919]),)
(array([4988]),)
(array([4991]),)
(array([4990]),)
(array([2463, 3238, 4221]),)
(array([2951, 4507]),)
(array([1433, 2271]),)
(array([2169, 4296]),)
(array([2159, 4289]),)
(array([3382]),)
(array([3385]),)
(array([3379]),)
(array([  21, 3921]),)
(array([2647, 3972, 45

(array([1278, 3689]),)
(array([ 660, 2693]),)
(array([1242, 2331, 2737]),)
(array([1235, 2336, 2732]),)
(array([1162, 4038]),)
(array([1172, 4018]),)
(array([ 452, 4057]),)
(array([ 885, 3756]),)
(array([ 854, 1991]),)
(array([ 531, 3734]),)
(array([ 777, 2703]),)
(array([ 802, 4801]),)
(array([1179, 3779]),)
(array([1020, 3772]),)
(array([ 169, 1169]),)
(array([1257, 2353, 2748]),)
(array([ 296, 4025]),)
(array([1260, 2356, 2752]),)
(array([ 419, 2063, 2679]),)
(array([ 616, 3493]),)
(array([1153, 3773]),)
(array([1009, 3653]),)
(array([109, 717]),)
(array([ 769, 3540]),)
(array([ 189, 2375]),)
(array([1201, 2314]),)
(array([ 279, 2035]),)
(array([ 219, 2021]),)
(array([ 484, 2099]),)
(array([ 47, 395]),)
(array([ 827, 3553]),)
(array([ 961, 2714, 2945]),)
(array([ 532, 3740]),)
(array([ 677, 3519]),)
(array([ 486, 2100, 4034]),)
(array([ 414, 3798]),)
(array([ 158, 1028]),)
(array([1115, 4928]),)
(array([ 652, 2176, 2691]),)
(array([ 587, 2579]),)
(array([ 974, 2645]),)
(array([412])

(array([ 305, 2042]),)
(array([ 345, 2057]),)
(array([1236, 2329, 2726]),)
(array([ 332, 2048, 2673]),)
(array([1987]),)
(array([ 331, 2044]),)
(array([1054, 2280]),)
(array([ 497, 2108]),)
(array([ 346, 2678]),)
(array([ 344, 2672]),)
(array([ 556, 1831]),)
(array([ 382, 3123]),)
(array([ 816, 3165]),)
(array([ 377, 3718]),)
(array([ 378, 2387]),)
(array([ 385, 2060]),)
(array([ 891, 2242]),)
(array([ 736, 2215]),)
(array([ 634, 3498]),)
(array([ 315, 4654]),)
(array([1621, 4760]),)
(array([ 921, 2246, 2709]),)
(array([1154, 1854]),)
(array([1012, 2272]),)
(array([ 326, 2543]),)
(array([ 280, 4637]),)
(array([ 274, 3791]),)
(array([ 271, 3704]),)
(array([895]),)
(array([1157, 2722, 2966]),)
(array([  27,  207, 3468]),)
(array([ 449, 2403]),)
(array([ 193, 2368]),)
(array([ 23, 203]),)
(array([ 184, 2013]),)
(array([ 252, 2024]),)
(array([1042, 3667]),)
(array([ 317, 2532]),)
(array([521]),)
(array([ 221, 2379]),)
(array([ 898, 2613]),)
(array([ 850, 4011, 4073]),)
(array([ 483, 2087])

(array([2561, 3135, 4273]),)
(array([3133, 4244]),)
(array([3183, 3668, 4524]),)
(array([3158, 4341]),)
(array([4186, 4708]),)
(array([3225, 4183]),)
(array([4179, 4700]),)
(array([2987, 4135]),)
(array([3810, 4118]),)
(array([3383, 3845]),)
(array([3113, 3216, 4107]),)
(array([4096, 4609]),)
(array([2983, 4141]),)
(array([3218, 4136]),)
(array([1483, 4480]),)
(array([1680, 2920]),)
(array([1803, 2795, 4251]),)
(array([2195, 4601]),)
(array([1681, 2919]),)
(array([ 954, 1663, 3029]),)
(array([1516, 4621]),)
(array([1088, 4891]),)
(array([1506, 4617]),)
(array([ 970, 4848]),)
(array([1503, 2519]),)
(array([1704, 3031, 3602]),)
(array([1491, 2505]),)
(array([1709, 3035, 3603]),)
(array([1517, 4625]),)
(array([1651, 4815]),)
(array([1648, 4820]),)
(array([1668, 2913]),)
(array([1655, 4824]),)
(array([4616]),)
(array([1437, 3111, 3443]),)
(array([2651, 3439, 4548]),)
(array([2274, 2957, 4531]),)
(array([2797, 4255]),)
(array([1797, 2791, 4253]),)
(array([1805, 4470]),)
(array([4539, 4909])

In [25]:
for i in range(len(unique_keys)):
    print(np.where(data[fields[4]] == unique_keys[i]))

(array([ 149,  307,  323,  368,  424,  485,  549,  551,  602,  662,  773,
        943,  970, 1214, 1396, 1440, 1591, 1594, 1694, 1877, 1893, 1917,
       1930, 2082, 2149, 2158, 2174, 2178, 2239, 2318, 2467, 2472, 2490,
       2497, 2537, 2539, 2676, 2704, 2779, 2828, 2834, 2931, 2937, 2944,
       3174, 3183, 3240, 3241, 3257, 3313, 3322, 3323, 3356, 3374, 3394,
       3470, 3668, 3742, 3826, 3848, 3900, 4032, 4044, 4087, 4117, 4223,
       4224, 4243, 4357, 4362, 4395, 4422, 4440, 4477, 4508, 4524, 4589,
       4737, 4848, 4893, 4927]),)
(array([0]),)
(array([4993]),)
(array([4995]),)
(array([6]),)
(array([4989]),)
(array([4980]),)
(array([4982]),)
(array([5]),)
(array([4985]),)
(array([17]),)
(array([15]),)
(array([4984]),)
(array([2]),)
(array([1]),)
(array([8]),)
(array([4979]),)
(array([21]),)
(array([4978]),)
(array([4977]),)
(array([10]),)
(array([13]),)
(array([4947]),)
(array([7]),)
(array([3]),)
(array([11]),)
(array([4]),)
(array([4948]),)
(array([4866]),)
(array([4968]),)


(array([4413]),)
(array([4460]),)
(array([4086]),)
(array([4081]),)
(array([4091]),)
(array([4090]),)
(array([4236]),)
(array([4089]),)
(array([4552]),)
(array([4079]),)
(array([4055]),)
(array([4080]),)
(array([4068]),)
(array([4060]),)
(array([4070]),)
(array([4077]),)
(array([4075]),)
(array([4062]),)
(array([4069]),)
(array([4066]),)
(array([4076]),)
(array([4074]),)
(array([4058]),)
(array([4072]),)
(array([4073]),)
(array([4057]),)
(array([4064]),)
(array([4067]),)
(array([4078]),)
(array([4053]),)
(array([4071]),)
(array([4056]),)
(array([4065]),)
(array([4059]),)
(array([4042]),)
(array([4034]),)
(array([4037]),)
(array([4029]),)
(array([4045]),)
(array([4043]),)
(array([4039]),)
(array([4052]),)
(array([4049]),)
(array([4050]),)
(array([4051]),)
(array([4041]),)
(array([4048]),)
(array([14]),)
(array([4040]),)
(array([4033]),)
(array([4026]),)
(array([4046]),)
(array([4036]),)
(array([4028]),)
(array([4022]),)
(array([4035]),)
(array([4054]),)
(array([4025]),)
(array([4008]),)

(array([3387]),)
(array([3362]),)
(array([3238]),)
(array([3309]),)
(array([3410]),)
(array([3366]),)
(array([3393]),)
(array([3262]),)
(array([3384]),)
(array([3385]),)
(array([3402]),)
(array([3316]),)
(array([3386]),)
(array([3378]),)
(array([3377]),)
(array([3244]),)
(array([3418]),)
(array([3443]),)
(array([3452]),)
(array([3411]),)
(array([3310]),)
(array([3263]),)
(array([3373]),)
(array([3279]),)
(array([3288]),)
(array([3420]),)
(array([3278]),)
(array([3285]),)
(array([3330]),)
(array([3399]),)
(array([3397]),)
(array([3259]),)
(array([3268]),)
(array([3236]),)
(array([3302]),)
(array([3359]),)
(array([3389]),)
(array([3277]),)
(array([3253]),)
(array([3252]),)
(array([3412]),)
(array([3202]),)
(array([3246]),)
(array([3436]),)
(array([3296]),)
(array([3286]),)
(array([3222]),)
(array([3388]),)
(array([3243]),)
(array([3206]),)
(array([3258]),)
(array([3304]),)
(array([3305]),)
(array([3417]),)
(array([3293]),)
(array([3382]),)
(array([3208]),)
(array([3409]),)
(array([3230])

(array([2526]),)
(array([2546]),)
(array([2644]),)
(array([2542]),)
(array([2534]),)
(array([2525]),)
(array([2593]),)
(array([2530]),)
(array([2506]),)
(array([2533]),)
(array([2627]),)
(array([2647]),)
(array([2633]),)
(array([2617]),)
(array([2607]),)
(array([2636]),)
(array([2635]),)
(array([2642]),)
(array([2606]),)
(array([2582]),)
(array([2577]),)
(array([2591]),)
(array([2583]),)
(array([2586]),)
(array([2660]),)
(array([2512]),)
(array([2655]),)
(array([2529]),)
(array([2558]),)
(array([2652]),)
(array([2613]),)
(array([2595]),)
(array([2571]),)
(array([2574]),)
(array([2614]),)
(array([2505]),)
(array([2573]),)
(array([2564]),)
(array([2500]),)
(array([2566]),)
(array([2609]),)
(array([2545]),)
(array([2559]),)
(array([2625]),)
(array([2628]),)
(array([2664]),)
(array([2578]),)
(array([2544]),)
(array([2552]),)
(array([2569]),)
(array([2579]),)
(array([2631]),)
(array([2563]),)
(array([2550]),)
(array([2659]),)
(array([2598]),)
(array([2608]),)
(array([2527]),)
(array([2596])

(array([2198]),)
(array([2014]),)
(array([2017]),)
(array([2021]),)
(array([2055]),)
(array([2140]),)
(array([2012]),)
(array([2300]),)
(array([1971]),)
(array([2007]),)
(array([1980]),)
(array([1973]),)
(array([1995]),)
(array([1970]),)
(array([2010]),)
(array([1984]),)
(array([2004]),)
(array([1992]),)
(array([1952]),)
(array([1962]),)
(array([1997]),)
(array([1999]),)
(array([1990]),)
(array([1951]),)
(array([1986]),)
(array([1994]),)
(array([2001]),)
(array([2002]),)
(array([1977]),)
(array([1998]),)
(array([1966]),)
(array([2016]),)
(array([2005]),)
(array([1964]),)
(array([1976]),)
(array([2009]),)
(array([1956]),)
(array([1983]),)
(array([1991]),)
(array([1978]),)
(array([1953]),)
(array([1988]),)
(array([1947]),)
(array([1961]),)
(array([1972]),)
(array([1989]),)
(array([1949]),)
(array([1974]),)
(array([1996]),)
(array([1967]),)
(array([1959]),)
(array([2003]),)
(array([1969]),)
(array([1958]),)
(array([1963]),)
(array([1965]),)
(array([1960]),)
(array([1993]),)
(array([1968])

(array([1392]),)
(array([1295]),)
(array([1339]),)
(array([1362]),)
(array([1354]),)
(array([1449]),)
(array([1294]),)
(array([1452]),)
(array([1306]),)
(array([1315]),)
(array([1323]),)
(array([1301]),)
(array([1404]),)
(array([1421]),)
(array([1445]),)
(array([1342]),)
(array([1344]),)
(array([1425]),)
(array([1436]),)
(array([1409]),)
(array([1293]),)
(array([1446]),)
(array([1283]),)
(array([1292]),)
(array([1285]),)
(array([1280]),)
(array([1282]),)
(array([1281]),)
(array([1286]),)
(array([1291]),)
(array([ 774, 1009]),)
(array([1203]),)
(array([1147]),)
(array([237]),)
(array([387]),)
(array([1252]),)
(array([639]),)
(array([1222]),)
(array([1016]),)
(array([469]),)
(array([1143]),)
(array([619]),)
(array([204]),)
(array([177]),)
(array([710]),)
(array([1047]),)
(array([862]),)
(array([1230]),)
(array([637]),)
(array([1262]),)
(array([403]),)
(array([1176]),)
(array([1270]),)
(array([1274]),)
(array([656]),)
(array([620]),)
(array([712]),)
(array([1266]),)
(array([1243]),)
(arra

(array([239]),)
(array([1213]),)
(array([1191]),)
(array([507]),)
(array([713]),)
(array([709]),)
(array([916]),)
(array([898]),)
(array([701]),)
(array([359]),)
(array([944]),)
(array([696]),)
(array([255]),)
(array([672]),)
(array([674]),)
(array([803]),)
(array([453]),)
(array([687]),)
(array([697]),)
(array([500]),)
(array([729]),)
(array([685]),)
(array([680]),)
(array([692]),)
(array([473]),)
(array([294]),)
(array([1198]),)
(array([1012]),)
(array([518]),)
(array([1278]),)
(array([1101]),)
(array([971]),)
(array([492]),)
(array([495]),)
(array([199]),)
(array([1067]),)
(array([449]),)
(array([636]),)
(array([1093]),)
(array([1155]),)
(array([813]),)
(array([708]),)
(array([308]),)
(array([588]),)
(array([589]),)
(array([867]),)
(array([581]),)
(array([584]),)
(array([206]),)
(array([579]),)
(array([805]),)
(array([236]),)
(array([322]),)
(array([194]),)
(array([394]),)
(array([1152]),)
(array([704]),)
(array([918]),)
(array([842]),)
(array([728]),)
(array([866]),)
(array([360]),

(array([188]),)
(array([967]),)
(array([313]),)
(array([296]),)
(array([470]),)
(array([1065]),)
(array([48]),)
(array([180]),)
(array([164]),)
(array([37]),)
(array([125]),)
(array([104]),)
(array([57]),)
(array([77]),)
(array([115]),)
(array([143]),)
(array([146]),)
(array([135]),)
(array([134]),)
(array([170]),)
(array([102]),)
(array([61]),)
(array([59]),)
(array([155]),)
(array([161]),)
(array([156]),)
(array([166]),)
(array([162]),)
(array([153]),)
(array([145]),)
(array([109]),)
(array([163]),)
(array([95]),)
(array([173]),)
(array([178]),)
(array([150]),)
(array([47]),)
(array([133]),)
(array([46]),)
(array([78]),)
(array([70]),)
(array([139]),)
(array([74]),)
(array([152]),)
(array([76]),)
(array([33]),)
(array([128]),)
(array([131]),)
(array([123]),)
(array([121]),)
(array([53]),)
(array([168]),)
(array([100]),)
(array([63]),)
(array([23]),)
(array([92]),)
(array([113]),)
(array([114]),)
(array([107]),)
(array([138]),)
(array([42]),)
(array([108]),)
(array([54]),)
(array([91]